#!/bin/bash

create_pid_file()
{
	touch $PID
}

delete_pid_file()
{
	rm $PID
}

exit_if_pid_file_exists()
{
	[ -f $PID ] && echo "PID file exists. Abort." && exit 1
}

SSH_PORT=22
BWLIMIT=5000
PID=/tmp/pi-backup.pid

WORKING_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

# Load configs.
source $WORKING_DIR/backup-client.conf

trap "echo Signal trap. Abort!; delete_pid_file; exit 1;" SIGINT SIGTERM

SSH_COMMAND="ssh -i $SSH_KEY -p $SSH_PORT"

# Full path on destination machine.
DEST_DIR=/mnt/$BACKUP_NAME

exit_if_pid_file_exists

create_pid_file

DEST=$BACKUP_USER@$ADDRESS:$DEST_DIR

set -x

rsync -az --bwlimit=$BWLIMIT -e "$SSH_COMMAND" --delete --delete-excluded $EXTRA_OPTS ${INCLUDES[@]} ${EXCLUDES[@]} $SOURCE $DEST/

delete_pid_file

