#!/bin/bash

RSYNC_OPTS="--delete --progress --verbose -az -e 'ssh -p 22'"

USER=pi
ADDRESS=192.168.1.154
DEST_DIR=/mnt/BTSync/will

DEST=$USER@$ADDRESS:$DEST_DIR

SRC=$HOME/BTSync/will

LOG=/var/log/backup-agent.log

function-run-backup()
{
	eval rsync $RSYNC_OPTS $SRC/Music $DEST/
	eval rsync $RSYNC_OPTS $SRC/Pictures $DEST/
	eval rsync --exclude ".encfs6.xml" $RSYNC_OPTS $HOME/BTSync/will/.crypt $DEST/
}

function-run-backup

date >> $LOG
