#!/bin/bash

RSYNC_OPTS="--delete --progress --verbose -az -e 'ssh -p 22'"

USER=
ADDRESS=
DEST_DIR=/mnt/BTSync/will

DEST=$USER@$ADDRESS:$DEST_DIR

SRC=$HOME/BTSync/will

FREQUENCY=10m

function-run-backup()
{
	eval rsync $RSYNC_OPTS $SRC/Music $DEST/
	eval rsync $RSYNC_OPTS $SRC/Pictures $DEST/
	eval rsync --exclude ".encfs6.xml" $RSYNC_OPTS $HOME/BTSync/will/.crypt $DEST/
}

while [ true ]
do
	function-run-backup

	sleep $FREQUENCY
done
