#!/bin/bash

RSYNC_OPTS="--delete --progress --verbose -az -e 'ssh -p 22'"

USER=
ADDRESS=

# Full path on destination machine.
DEST_DIR=

DEST=$USER@$ADDRESS:$DEST_DIR

LOG=backup-agent.log

function-run-backup()
{
	eval rsync $RSYNC_OPTS $HOME/BTSync/will/Music $DEST/
	eval rsync $RSYNC_OPTS $HOME/BTSync/will/Pictures $DEST/
	eval rsync --exclude ".encfs6.xml" $RSYNC_OPTS $HOME/BTSync/will/.crypt $DEST/
}

function-run-backup

date >> $LOG
