install:
	cp ./backup-agent-control /etc/init.d/
	update-rc.d backup-agent-control defaults
	cp ./backup-agent /usr/local/bin/
	chmod +x /etc/init.d/backup-agent-control
	chmod +x /usr/local/bin/backup-agent

uninstall:
	update-rc.d -f backup-agent-control remove
	rm -f /etc/init.d/backup-agent-control
	rm -f /usr/local/bin/backup-agent

reinstall: uninstall install
