install:
	cp ./backup-agent /usr/local/bin/
	chmod +x /usr/local/bin/backup-agent
	./add-to-cron.sh
	touch /var/log/backup-agent.log
	chmod 777 /var/log/backup-agent.log

uninstall:
	rm -f /usr/local/bin/backup-agent
	rm -f /var/log/backup-agent.log
	echo "Remove the crontab entry manually!!!"

reinstall: uninstall install
