#!/bin/bash

# Default configs.

SSH_USER=pi
SSH_PORT=22
SSH_KEY=$HOME/.ssh/id_rsa
BWLIMIT=5000
BACKUP_NAME=$(hostname)

# Load configs overrides.

SCRIPT_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

. $SCRIPT_DIR/config

# Backup commands.

trap "echo Signal trap. Abort!; exit 1;" SIGINT SIGTERM

RSYNC_SSH="ssh -i $SSH_KEY -p $SSH_PORT"
RSYNC_OPTS="--delete --progress --verbose -az --bwlimit=$BWLIMIT"

# Full path on destination machine.
DEST_DIR=/bak/$BACKUP_NAME

LOG=$SCRIPT_DIR/pi-backup.log

DEST=$SSH_USER@$ADDRESS:$DEST_DIR

if (! ssh -i $SSH_KEY -p $SSH_PORT $SSH_USER@$ADDRESS "[ -d $DEST_DIR ]")
then
  echo "Backup destination does not exist. Abort."
  exit 1
fi

for directory in ${DIRECTORIES[@]}
do
	date >> $directory/.backup-tracker.log	

	# If one fails, abort.  Don't bother trying the others.
	rsync $RSYNC_OPTS -e "$RSYNC_SSH" $directory $DEST/ || break
done

date >> $LOG
