#!/bin/bash

trap "echo Signal trap. Abort!; exit 1;" SIGINT SIGTERM

CWD=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

. $CWD/config

BWLIMIT_DEFAULT=5000
BWLIMIT=${BWLIMIT:-$BWLIMIT_DEFAULT}

RSYNC_SSH="ssh -p $SSH_PORT"
RSYNC_OPTS="--delete --progress --verbose -az --bwlimit=$BWLIMIT"

# Full path on destination machine.
DEST_DIR=/bak/$BACKUP_NAME

DEST=$USER@$ADDRESS:$DEST_DIR

LOG=pi-backup.log

for directory in ${DIRECTORIES[@]}
do
	# If one fails, abort.  Don't try the others.
	rsync $RSYNC_OPTS -e "$RSYNC_SSH" $directory $DEST/ || break
done

date >> $CWD/$LOG
